export let productos = [
    {
        "id":1,
        "imagenes": ["producto.webp","producto2.webp"],
        "nombre": "Notebook PEPEresoso",
        "descripción": "Esta notebook es, en efecto, una notebook. _2024",
        "stock": 5,
        "precio": 364533327,
        "dim_alto":5,
        "dim_ancho":10,
        "dim_prof":23,
        "peso":1300,
        "estado": 1,
        "home":1,
        "off":0,
        "envio_gratis":1,
        "etiquetas":["moda","notebooks", "estudio"],
        "variante":["blanco", "negro", "rosa gold"]
    },
    {
        "id":2,
        "imagenes": ["producto2.webp","producto.webp"],
        "nombre": "Notebook POPA",
        "descripción": "Esta notebook es una computadora personal. _2021",
        "stock": 1,
        "precio": 113293331,
        "dim_alto":3,
        "dim_ancho":7,
        "dim_prof":11,
        "peso":3420,
        "estado": 1,
        "home":1,
        "off":15,
        "envio_gratis":0,
        "etiquetas":["notebooks", "trabajo"],
        "variante":["silver"]
    },
    {
        "id":3,
        "imagenes": ["producto2.webp","producto.webp"],
        "nombre": "Notebook aidoaijs",
        "descripción": "Esta notebook es una computadora personal. _2021",
        "stock": 1,
        "precio": 15593300,
        "dim_alto":3,
        "dim_ancho":7,
        "dim_prof":11,
        "peso":3420,
        "estado": 1,
        "home":1,
        "off":10,
        "envio_gratis":0,
        "etiquetas":["notebooks", "trabajo"],
        "variante":["silver"]
    }
]
